name: CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write   # needed to push to GHCR

env:
  IMAGE_NAME: ghcr.io/ingsis-team/printscript-service-2025

jobs:
  publish_to_registry:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v1.2
        with:
          length: 8

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=sha-${{ steps.short-sha.outputs.sha }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # << fix: guaranteed non-empty
          password: ${{ secrets.GITHUB_TOKEN }}  # builtin token, has packages:write

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |                           # pass creds into Docker build
            GITHUB_USERNAME=${{ github.actor }}   # << fix: no secret needed
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
