name: CD Pipeline

on:
  push:
    branches: [ main, dev ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/ingsis-team/printscript-service-2025

jobs:
  publish_to_registry:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate short commit SHA
        id: short-sha
        uses: benjlevesque/short-sha@v1.2
        with:
          length: 8

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch                          
            type=raw,value=sha-${{ steps.short-sha.outputs.sha }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |  
            GITHUB_USERNAME=${{ github.actor }}
            GITHUB_TOKEN=${{ github.token }}
